### ISSUE TITLE
popUpCart

### ISSUE THREAD

**Issue by AdreanRodriguez** [divperedi/knowledgeKnightsAgile#10]
Som användare vill jag se order sidan för att se information om beställningen.
- [ ] Pop-up ruta för innehållet från varukorgs ikonen.
- [ ] H1 Din beställning.
- [ ] Produktnamn, pris, total & antal där man kan lägga till och ta bort.
- [ ] Köpknapp som ska leda till status-sidan

**Comment by divperedi** [comment]
råkade skapa branch från main, därför stängde issue och öppnade ny
